# Form implementation generated from reading ui file 'd:\OwO\Python\MIR\iniciarSesion.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(480, 620)
        Dialog.setStyleSheet("background-color: rgb(54, 54, 54);")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(140, 110, 211, 61))
        self.label.setStyleSheet("color: rgb(225, 225, 225);font-size:28pt")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(60, 220, 71, 31))
        self.label_2.setStyleSheet("font-size:15pt;\n"
"color: rgb(255, 0, 127);")
        self.label_2.setObjectName("label_2")
        self.email_in = QtWidgets.QLineEdit(Dialog)
        self.email_in.setGeometry(QtCore.QRect(190, 220, 241, 31))
        self.email_in.setStyleSheet("font-size:15pt;\n"
"color: rgb(225, 225, 225);")
        self.email_in.setObjectName("email_in")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(60, 310, 101, 31))
        self.label_3.setStyleSheet("font-size:15pt;\n"
"color: rgb(255, 0, 127);")
        self.label_3.setObjectName("label_3")
        self.contra_in = QtWidgets.QLineEdit(Dialog)
        self.contra_in.setGeometry(QtCore.QRect(190, 310, 241, 31))
        self.contra_in.setStyleSheet("font-size:15pt;\n"
"color: rgb(225, 225, 225);")
        self.contra_in.setObjectName("contra_in")
        self.boton_ingreso = QtWidgets.QPushButton(Dialog)
        self.boton_ingreso.setGeometry(QtCore.QRect(330, 430, 101, 31))
        self.boton_ingreso.setStyleSheet("background-color: rgb(167, 168, 167);\n"
"font-size:14pt;\n"
"color: rgb(255, 255, 255);")
        self.boton_ingreso.setObjectName("boton_ingreso")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(200, 380, 121, 16))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.boton_crear_cuenta = QtWidgets.QPushButton(Dialog)
        self.boton_crear_cuenta.setGeometry(QtCore.QRect(350, 380, 75, 23))
        self.boton_crear_cuenta.setStyleSheet("color: rgb(255, 255, 255);")
        self.boton_crear_cuenta.setObjectName("boton_crear_cuenta")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Iniciar sesión"))
        self.label_2.setText(_translate("Dialog", "Correo"))
        self.label_3.setText(_translate("Dialog", "Contraseña"))
        self.boton_ingreso.setText(_translate("Dialog", "Ingresar"))
        self.label_4.setText(_translate("Dialog", "¿No tiene una cuenta?"))
        self.boton_crear_cuenta.setText(_translate("Dialog", "Crear cuenta"))
